name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 2.1.0
homepage: https://github.com/sbis04/video_trimmer

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  video_player: 
  ffmpeg_kit_flutter: 5.1.0-LTS
  video_thumbnail: 
  path_provider: 
  intl: 
  path: 
  transparent_image: 

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.1

flutter:
